/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qsixolusiprqgxukojgw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzaXhvbHVzaXBycWd4dWtvamd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MjE5OTgsImV4cCI6MjA4OTM5Nzk5OH0.AfLaqCnA9qmxKNtM7suiUiMFF03gxuv-BqH1vz8K-y0"